name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
    
jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install base dependencies
        run: python -m pip install --upgrade pip
      - name: Install dev tools
        run: |
          pip install poetry
          poetry config virtualenvs.create false 
          poetry install --no-interaction --no-root
          
      - name: Clear mypy cache
        run: rm -rf .mypy_cache

      - name: Run MyPy (flask)
        working-directory: ./flask_version  
        run: mypy .

      - name: Run Black
        run: black --check --diff .

      - name: Run Isort
        run: isort --check-only --profile black .

      - name: Run Flake8
        run: flake8 .
